services:
  postgresql:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: "cr.yandex/crp3ftp1b7dveeagva5g/madr-postgres:latest"
    ports:
      - "5432:5432"
    networks:
      mynetwork:
    environment:
      - TZ=Europe/Moscow
  madr:
    build: .
    image: "cr.yandex/crp3ftp1b7dveeagva5g/madr-go-app:latest"
    ports:
      - "8080:8080"
    networks:
      mynetwork:
    environment:
      - TZ=Europe/Moscow
      - DB_CONN_STR=user=postgres dbname=postgres host=postgresql port=5432 sslmode=disable
      - TOKEN_EXPIRATION_TIME=48 # hours
      - TOKEN_SECRET=secret
      - SALT_LENGTH=16
  madr-react-app:
    build:
      context: ./madr_web_app
      dockerfile: Dockerfile
    image: "cr.yandex/crp3ftp1b7dveeagva5g/madr-react:latest"
    ports:
      - "80:80"
  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --search-path=/liquibase/changelog/
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - liquibase:/liquibase/changelog
    networks:
      mynetwork:

networks:
  mynetwork:
    driver: bridge

volumes:
  liquibase:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './db'