services:
  madr:
    build: .
    ports:
      - "8080:8080"
    networks:
      mynetwork:
    environment:
      - TZ=Europe/Moscow
  site:
    build: ./madr_web_app
    ports:
      - "80:3000"
    networks:
      mynetwork:

networks:
  mynetwork:
    driver: bridge