services:
  postgresql:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      mynetwork:
    environment:
      - TZ=Europe/Moscow
      - DB_CONN_STR=user=postgres dbname=postgres host=postgresql port=5432 sslmode=disable
      - TOKEN_EXPIRATION_TIME=48 # hours
      - TOKEN_SECRET=secret
      - SALT_LENGTH=16
  madr:
    build: .
    ports:
      - "8080:8080"
    networks:
      mynetwork:
    environment:
      - TZ=Europe/Moscow
  site:
    build: ./madr_web_app
    ports:
      - "80:3000"
    networks:
      mynetwork:

networks:
  mynetwork:
    driver: bridge