// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	"github.com/ogniloud/madr/internal/flashcards/models"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// DeleteFlashcardFromDeck provides a mock function with given fields: cardId
func (_m *Storage) DeleteFlashcardFromDeck(cardId int) error {
	ret := _m.Called(cardId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(cardId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserDeck provides a mock function with given fields: userId, id
func (_m *Storage) DeleteUserDeck(userId int, id int) error {
	ret := _m.Called(userId, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userId, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDecksByUserId provides a mock function with given fields: id
func (_m *Storage) GetDecksByUserId(id int) (models.Decks, error) {
	ret := _m.Called(id)

	var r0 models.Decks
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Decks, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Decks); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Decks)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFlashcardById provides a mock function with given fields: id
func (_m *Storage) GetFlashcardById(id int) (models.Flashcard, error) {
	ret := _m.Called(id)

	var r0 models.Flashcard
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Flashcard, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Flashcard); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Flashcard)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFlashcardsIdByDeckId provides a mock function with given fields: id
func (_m *Storage) GetFlashcardsIdByDeckId(id int) ([]int, error) {
	ret := _m.Called(id)

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]int, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []int); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeitnerByUserIdCardId provides a mock function with given fields: id, flashcardId
func (_m *Storage) GetLeitnerByUserIdCardId(id int, flashcardId int) (models.UserLeitner, error) {
	ret := _m.Called(id, flashcardId)

	var r0 models.UserLeitner
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (models.UserLeitner, error)); ok {
		return rf(id, flashcardId)
	}
	if rf, ok := ret.Get(0).(func(int, int) models.UserLeitner); ok {
		r0 = rf(id, flashcardId)
	} else {
		r0 = ret.Get(0).(models.UserLeitner)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(id, flashcardId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserInfo provides a mock function with given fields: uid
func (_m *Storage) GetUserInfo(uid int) (models.UserInfo, error) {
	ret := _m.Called(uid)

	var r0 models.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.UserInfo, error)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(int) models.UserInfo); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Get(0).(models.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutAllFlashcards provides a mock function with given fields: id, cards
func (_m *Storage) PutAllFlashcards(id int, cards []models.Flashcard) error {
	ret := _m.Called(id, cards)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []models.Flashcard) error); ok {
		r0 = rf(id, cards)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutAllUserLeitner provides a mock function with given fields: uls
func (_m *Storage) PutAllUserLeitner(uls []models.UserLeitner) error {
	ret := _m.Called(uls)

	var r0 error
	if rf, ok := ret.Get(0).(func([]models.UserLeitner) error); ok {
		r0 = rf(uls)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutNewDeck provides a mock function with given fields: config
func (_m *Storage) PutNewDeck(config models.DeckConfig) error {
	ret := _m.Called(config)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.DeckConfig) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLeitner provides a mock function with given fields: ul
func (_m *Storage) UpdateLeitner(ul models.UserLeitner) error {
	ret := _m.Called(ul)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.UserLeitner) error); ok {
		r0 = rf(ul)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
